name: Snyk Test with All Monitors

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@master

      # Run Snyk to check for vulnerabilities
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test --all-projects
