name: Snyk Security Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: # Allows manual triggers for this workflow

permissions:
  contents: read
  security-events: write # Needed for uploading SARIF results

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Snyk CLI
      - name: Set up Snyk CLI
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Run Snyk Code analysis (no SARIF file storage)
      - name: Snyk Code test
        id: snyk_code_test
        run: |
          snyk code test || echo "Snyk Code test failed, but continuing."
          echo "Exit code: $?"

      # Run Snyk Open Source monitor
      - name: Snyk Open Source monitor
        id: snyk_monitor
        run: |
          snyk monitor --all-projects || echo "Snyk Open Source monitor failed, but continuing."
          echo "Exit code: $?"

      # Post status
      - name: Check results
        run: |
          if [[ ${{ steps.snyk_code_test.outcome }} == "failure" ]]; then
            echo "Snyk Code test encountered issues."
          fi
          if [[ ${{ steps.snyk_monitor.outcome }} == "failure" ]]; then
            echo "Snyk Open Source monitor encountered issues."
          fi
